[package]
name = "coap-ace-poc-firmware"
version = "0.1.0"
edition = "2021"
authors = [ "EDF, developed in collaboration with Christian Amsüss" ]
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

default = [ "hardware-nrf52dk" ]
# Not parametrizing into dependencies yet
hardware-nrf52dk = []

[profile.release]
# to get better output from defmt / probe-run
debug = 2

[dependencies]
heapless = "*"
# Providing general entry
cortex-m-rt = "0.7.0"

# Debug output
defmt = "0.3"
defmt-rtt = "0.3.2"
panic-probe = { version = "0.3", features= ["print-defmt"] }

# Providing an asynchronous runtime needed for the softdevice
embassy-executor = { version = "0.1.0", features = ["nightly", "defmt", "defmt-timestamp-uptime"]}
embassy-util = "0.1.0"
# ... and helpers to get the 'static Server we need in the runners
static_cell = "1"

# Hardware support
nrf-softdevice = { version = "0.1.0", features = ["defmt", "nrf52832", "s132", "ble-peripheral", "critical-section-impl", "ble-gatt-server" ] }
# We could pick 112, that would suffice from the required features, but
# building on 132 to ensure we can migrate over.
nrf-softdevice-s132 = "0.1.1"

# LEDs and buttons, really
nrf52832-hal = "0.15.1"

# Providing time for defmt output
embassy-nrf = { version = "0.1.0", features = [ "nightly", "defmt", "nrf52832", "gpiote", "time-driver-rtc1" ]}

[patch.crates-io]
# None of these are available on crates.io yet
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "d881f3ad9186cf3279aa1ba27093bad94035c186" }
embassy-util = { git = "https://github.com/embassy-rs/embassy", rev = "d881f3ad9186cf3279aa1ba27093bad94035c186" }
embassy-nrf = { git = "https://github.com/embassy-rs/embassy", rev = "d881f3ad9186cf3279aa1ba27093bad94035c186" }
embassy-macros = { git = "https://github.com/embassy-rs/embassy", rev = "d881f3ad9186cf3279aa1ba27093bad94035c186" }

nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice", rev = "e1e4e2a2c2e9a8243368214fac02532e79c127a8" }
nrf-softdevice-s132 = { git = "https://github.com/embassy-rs/nrf-softdevice", rev = "e1e4e2a2c2e9a8243368214fac02532e79c127a8" }
