# SPDX-FileCopyrightText: Copyright 2022 EDF (Électricité de France S.A.)
# SPDX-License-Identifier: BSD-3-Clause
# See README for all details on copyright, authorship and license.
as_uri: https://as.coap.amsuess.com/token
audience: d01
issuer: AS
key: 953661edfd116765a511cf25c88025896071dd4680946cb4361e511d3e3ecf16
