# SPDX-FileCopyrightText: Copyright 2022 EDF (Électricité de France S.A.)
# SPDX-License-Identifier: BSD-3-Clause
# See README for all details on copyright, authorship and license.
as_uri: https://as.coap.amsuess.com/token
audience: d06
issuer: AS
key: a56ebd03463de6d3f80060a32e079d9cd3553633c77f24941f82d6a6a42a1175
